blackpearl/associados/urls.py
from django.urls import path, include, re_path

from blackpearl.associados import views
from blackpearl.associados.views import HomeTemplateView, AssociadoUpdateView, AssociadoDeleteView, AssociadoDetailView, \
    AssociadoCreateView, DependenteCreateView, DependenteUpdateView, DependenteDeleteView, ImportExcelView, \
    ConsultaIdadeAssocView

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home_assoc'),
    path('<int:pk>/', AssociadoDetailView.as_view(), name='visualizar_associado'),
    path('editar/<int:pk>/', AssociadoUpdateView.as_view(), name='editar_associado'),
    path('excluir/<int:pk>/', AssociadoDeleteView.as_view(), name='excluir_associado'),
    path('cadastrar/', AssociadoCreateView.as_view(), name='cadastrar_associado'),

    path('idadeassoc/consulta/', ConsultaIdadeAssocView.as_view(), name='consulta_data_nascimento_assoc'),
    path('cadastrardependentes/', DependenteCreateView.as_view(), name='cadastrar_dependentes'),
    path('editardependente/<int:pk>/', DependenteUpdateView.as_view(), name='editar_dependente'),
    path('excluirdependente/<int:pk>/', DependenteDeleteView.as_view(), name='excluir_dependente'),

    ##path('importExcel/', views.importExcel, name='importExcel'),
    path('importExcel/', ImportExcelView.as_view(), name='importExcel'),

]

blackpearl/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blackpearl.usuarios.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('blackpearl.usuarios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('associados/', include('blackpearl.associados.urls')),
    path('convenios/', include('blackpearl.convenios.urls')),
    path('cobrancas/', include('blackpearl.cobrancas.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blackpearl/associados/models.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
# Create your models here.

from django.db.models import signals
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django.urls import reverse

ESTADOS_CHOICES = [
    ("AC", "Acre"),
    ("AL", "Alagoas"),
    ("AP", "Amapá"),
    ("AM", "Amazonas"),
    ("BA", "Bahia"),
    ("CE", "Ceará"),
    ("DF", "Distrito Federal"),
    ("ES", "Espírito Santo"),
    ("GO", "Goiás"),
    ("MA", "Maranhão"),
    ("MT", "Mato Grosso"),
    ("MS", "Mato Grosso do Sul"),
    ("MG", "Minas Gerais"),
    ("PA", "Pará"),
    ("PB", "Paraíba"),
    ("PR", "Paraná"),
    ("PE", "Pernambuco"),
    ("PI", "Piauí"),
    ("RJ", "Rio de Janeiro"),
    ("RN", "Rio Grande do Norte"),
    ("RS", "Rio Grande do Sul"),
    ("RO", "Rondônia"),
    ("RR", "Roraima"),
    ("SC", "Santa Catarina"),
    ("SP", "São Paulo"),
    ("SE", "Sergipe"),
    ("TO", "Tocantins")
]

ORGEMISSOR_CHOICES = [
    ("SSP", "Secretaria de Segurança Pública"),
    ("SSPDS", "Secretaria de Segurança Pública e Defesa Social"),
    ("PF", "Polícia Federal"),
    ("PC", "Polícia Civil"),
    ("XXX", "Orgão Estrangeiro"),
    ("ZZZ", "Outro"),
]

ESTADOCIVIL_CHOICES = [
    ('S', 'Solteiro(a)'),
    ('C', 'Casado(a)'),
    ('D', 'Divorciado(a)'),
    ('V', 'Viúvo(a)'),
    ('U', 'União Estável'),
    ('O', 'Outro')
]

SEXO_CHOICES = [
('m', 'Masculino'),
('f', 'Feminino')

]

GRAUS_PARENTESCO_CHOICES = [
    ('P', 'Pai'),
    ('M', 'Mãe'),
    ('F', 'Filho(a)'),
    ('C', 'Cônjuge'),
    ('I', 'Irmão(ã)'),
    ('O', 'Outro'),
]

ASSOCIACAO_CHOICES = [
    ('ag', 'Agredado(a)'),
    ('fiativo', 'Filiado(a) da Ativa'),
    ('fiaposent', 'Filiado(a) Aposentado(a)'),
    ('func', 'Funcionário(a) da Associação'),
    ('desfi', 'Desfiliado(a)')
]

class Base(models.Model):
    criado = models.DateField('Data de Criação', auto_now_add=True)
    modificado = models.DateField('Data de Atualização', auto_now_add=True)
    ativo = models.BooleanField('Ativo?', default=True)

    class Meta:
        abstract = True

class Empresa(Base):
    nome = models.CharField('Nome da empresa', max_length= 100)
    estado = models.CharField('Estado de atuação', max_length=20, choices= ESTADOS_CHOICES)

    def __str__(self):
        return self.nome


class Associado(Base):
    DoesNotExist = None
    nomecompleto = models.CharField('Nome Completo', max_length=300)

    dataNascimento = models.DateField('Data de Nascimento')
    sexo = models.CharField('Sexo', max_length=1, choices=SEXO_CHOICES)

    cpf = models.CharField('CPF', max_length=11)
    identidade = models.CharField('Identidade', max_length=20, default='', blank=True)
    orgemissor = models.CharField('Órgão Emissor', max_length= 6, choices=ORGEMISSOR_CHOICES, default='',  blank=True)
    estadocivil = models.CharField('Estado Civil', max_length= 2, choices=ESTADOCIVIL_CHOICES, default='', blank=True)

    dataAssociacao = models.DateField('Data de Associação')
    associacao = models.CharField('Associação', max_length=50, choices=ASSOCIACAO_CHOICES, default= '')
    matricula = models.IntegerField('Matricula', blank=True, default=0)
    empresa  = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name='empresa')

    email = models.EmailField('e-mail', )
    dddNumeroContato = models.CharField('DDD', max_length=2)
    numeroContato = models.CharField('Celular', max_length=9)

    slug = models.SlugField('Slug', max_length=100, blank=True, editable=False)

    # Endereço
    cep = models.CharField('CEP', max_length=9,  default='',  blank=True)
    logradouro = models.CharField('Logradouro', max_length=200, default='',  blank=True)
    num = models.IntegerField('Número', default='',  blank=True)
    bairro = models.CharField('Bairro', max_length=100, default='',  blank=True)
    cidade = models.CharField('Cidade', max_length=100, default='',  blank=True)
    estado = models.CharField('Estado (UF)', max_length=2, choices=ESTADOS_CHOICES, default='', blank=True)

    def save(self, *args, **kwargs):
        self.nomecompleto = self.nomecompleto.upper()
        self.logradouro = self.logradouro.upper()
        self.bairro = self.bairro.upper()
        self.cidade = self.cidade.upper()

        self.estado = self.estado.upper()

        super().save(*args, **kwargs)
    def __str__(self):
        return '{}'.format(self.nomecompleto.title())

    def get_nomecompleto_display(self):
        return self.nomecompleto.title()
    def get_sexo_display(self):
        return dict(SEXO_CHOICES)[self.sexo]
    def get_associacao_display(self):
        return dict(ASSOCIACAO_CHOICES)[self.associacao]
    def get_estadocivil_display(self):
        if self.estadocivil == '':
            return 'Não Informado'
        return dict(ESTADOCIVIL_CHOICES)[self.estadocivil]
    def get_absolute_url(self):
        return reverse("editar", kwargs={"pk": self.pk})

    def get_quantidade_dependentes(self):
        return self.dependentes.count()

class Dependente(Base):
    titular = models.ForeignKey(Associado, on_delete=models.CASCADE, related_name='dependentes')
    nomecompleto = models.CharField('Nome Completo', max_length=300)
    dataNascimento = models.DateField('Data de Nascimento')
    sexo = models.CharField('Sexo', max_length=1, choices=SEXO_CHOICES)

    cpf = models.CharField('CPF', max_length=11)
    identidade = models.CharField('Identidade', max_length=20, default='', blank=True)
    orgemissor = models.CharField('Órgão Emissor', max_length=6, choices=ORGEMISSOR_CHOICES, default='', blank=True)
    grauparentesco = models.CharField('Grau de Parentesco', max_length=6, choices=GRAUS_PARENTESCO_CHOICES, default='')


    def get_sexo_display(self):
        return dict(SEXO_CHOICES)[self.sexo]
    def get_grauparentesco_display(self):
        return dict(GRAUS_PARENTESCO_CHOICES)[self.grauparentesco]
    def get_nomecompleto_display(self):
        return self.nomecompleto.title()
    def get_absolute_url(self):
        return reverse("editar", kwargs={"pk": self.pk})
    def save(self, *args, **kwargs):
        self.nomecompleto = self.nomecompleto.upper()
        super().save(*args, **kwargs)
    def __str__(self):
        return '{} '.format(self.nomecompleto)
    ##dict(GRAUS_PARENTESCO_CHOICES)[self.grauparentesco].upper())
def associado_pre_save(instance, sender, **kwargs):
    instance.slug = slugify(instance.nomecompleto)
signals.pre_save.connect(associado_pre_save, sender=Associado)

def dependente_pre_save(instance, sender, **kwargs):
    instance.slug = slugify(instance.nomecompleto)
signals.pre_save.connect(dependente_pre_save, sender=Dependente)



class FileUploadExcelModel(Base):
    nome = models.CharField(max_length=100)
    arquivo = models.FileField()

blackpearl/cobrancas/views/homeView.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView


from blackpearl.cobrancas.models.faturaCobrancaModels import CobrancaPlanoSaude, CobrancaPlanoOdontologico, FaturaCobranca

@method_decorator(login_required, name='dispatch')
class FaturaCobrancaListView(ListView):
    template_name = 'home_cob.html'

    context_object_name = 'list_objs'
    paginate_by = 10

    def get_queryset(self):
        cobrancas_plano_saude = CobrancaPlanoSaude.objects.all()
        cobrancas_plano_odontologico = CobrancaPlanoOdontologico.objects.all()

        todas_cobrancas = list(cobrancas_plano_saude) + list(cobrancas_plano_odontologico)

        todas_cobrancas.sort(key=lambda x: x.situacao)
        return todas_cobrancas


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(FaturaCobrancaListView, self).get_context_data(**kwargs)
        context['list_obs'] = self.get_queryset()

        return context

blackpearl/convenios/views/homeViews.py
from io import BytesIO
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from reportlab.pdfgen import canvas
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from blackpearl.convenios.models.cartaoVolusModels import FaturaCartao


@method_decorator(login_required, name='dispatch')
class HomeTemplateView(TemplateView):
    template_name = 'convenios/home_cob.html'

    def get_context_data(self, **kwargs):
        context = super(HomeTemplateView, self).get_context_data(**kwargs)
        return context


"""
def exportar(request):
    empresa_selecionada = request.GET.get('inputGroupSelectEmpresa')
    data_inicial = request.GET.get('start_date')
    data_final = request.GET.get('end_date')
    tipoArquivo_selecionado = request.GET.get('inputGroupSelectTipoArquivo')

    print(f"{empresa_selecionada}, {data_inicial}, {data_final}")

    if data_inicial and data_final and empresa_selecionada and tipoArquivo_selecionado:
        # Filtra as faturas pelo intervalo de datas e pelo nome da empresa
        if empresa_selecionada == '5':
            faturas = FaturaCartao.objects.filter(
                competencia__gte=data_inicial, competencia__lte=data_final
            ).order_by('competencia')

            nome_arq = 'faturas_{}_{}'.format(data_inicial, data_final)
        else:
            faturas = FaturaCartao.objects.filter(
                cartao__titular__empresa_id=empresa_selecionada,
                competencia__gte=data_inicial, competencia__lte=data_final
            ).order_by('competencia')
            nome_arq = 'fatura_{}_{}'.format(data_inicial, data_final)

        return exporttofile(faturas=faturas,
                            nome_arq=nome_arq,
                            tipoArquivo_selecionado=tipoArquivo_selecionado)

    return reverse_lazy('listagemfaturas')


def exporttofile(faturas, nome_arq, tipoArquivo_selecionado):
    global response
    filename = f"{nome_arq}"

    if tipoArquivo_selecionado == '1':

        quant_faturas = faturas.count()
        buffer = BytesIO()
        pdf = canvas.Canvas(buffer)
        y = 750  # Posição y inicial
        for fatura in faturas:
            if y <= 50:
                pdf.showPage()
                y = 750
            # Escreve o título da fatura
            pdf.drawString(100, y, "Titular do Cartão: {}".format(fatura.cartao.titular.nomecompleto))
            y -= 20  # Move para a próxima linha
            pdf.drawString(100, y, "Empresa: {}".format(fatura.cartao.titular.empresa.nome))
            y -= 20  # Move para a próxima linha
            # Escreve as informações da fatura
            pdf.drawString(100, y, "Competência: {}".format(fatura.competencia))
            y -= 20
            pdf.drawString(100, y, "Valor: {}".format(fatura.valorComTaxa))
            y -= 40  # Move duas linhas para baixo

        pdf.save()
        # Define o nome do arquivo PDF
        filename = filename + ".pdf"
        # Envia o PDF para o navegador como um arquivo de download
        response = HttpResponse(content_type='application/pdf')

        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        buffer.seek(0)

        response.write(buffer.read())

        buffer.close()
    elif tipoArquivo_selecionado == '2':
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = nome_arq
        # Escreve os dados da lista de faturas na planilha
        ws['A1'] = "Titular - Associado(a)"
        ws['B1'] = "Empresa"
        ws['C1'] = "Competêcia"
        ws['D1'] = "Valor"


        for i, fatura in enumerate(faturas):
            ws.cell(row=i + 2, column=1, value=fatura.cartao.titular.nomecompleto)
            ws.cell(row=i + 2, column=2, value=fatura.cartao.titular.empresa.nome)
            ws.cell(row=i + 2, column=3, value=fatura.competencia)
            ws.cell(row=i + 2, column=4, value=fatura.valorComTaxa)

        # Cria uma resposta HTTP com o arquivo XLSX
        response = HttpResponse(content_type='application/xlsx')
        response['Content-Disposition'] = f'attachment; filename={nome_arq}.xlsx'
        wb.save(response)


    elif tipoArquivo_selecionado == '3':
        faturas_txt = ''
        for fatura in faturas:
            matricula = str(fatura.cartao.titular.matricula).zfill(6)
            valorComTaxa = str(fatura.valorComTaxa)[:4].replace('.', '').zfill(12)
            faturas_txt += '{} {}\n'.format(matricula, valorComTaxa)

        response = HttpResponse(faturas_txt, content_type='text/plain')
        response['Content-Disposition'] = f'attachment; filename="{nome_arq}.txt'

    return response
"""

blackpearl/associados/templates/associados/associado_detalhes.html
{% extends "base_sidebar.html" %}
{% block content %}
{% load bootstrap5 %}
{% load static %}

        <div class="container-fluid ">
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h5>Associado: {{associado.nomecompleto}}</h5>
                                </div>
                                <div class="card-body">
                                    <h5>Titular: <strong>{{associado.nomecompleto}}</strong></h5>
                                     <div class="row">
                                         <div class="col-md-6">
                                             <h5>Dados Pessoais</h5>
                                             <ul class="list-unstyled">
                                                    <li>Data de Nascimento: <strong>{{ associado.dataNascimento }}</strong></li>
                                                    <li>Sexo: <strong>{{ associado.get_sexo_display }}</strong></li>
                                                    <li>CPF: <strong>{{ associado.cpf }}</strong></li>
                                                    <li>Número da identidade: <strong>{{ associado.identidade }}</strong></li>
                                                    <li>Estado Civil <strong>{{ associado.get_estadocivil_display }}</strong></li>
                                             </ul>
                                             <h5>Associação</h5>
                                             <ul class="list-unstyled">
                                                 <li>Tipo: <strong>{{associado.get_associacao_display}}</strong></li>
                                                 <li>Data da Asssociação: <strong>{{ associado.dataAssociacao }}</strong></li>
                                                 <li>Empresa: <strong>{{ associado.empresa }}</strong></li>
                                                 <li>Matricúla: <strong>{{ associado.matricula }}</strong></li>
                                             </ul>
                                             <h5>Contatos</h5>
                                             <ul class="list-unstyled">
                                                 <li>Celular: <strong>({{associado.dddNumeroContato}}) {{ associado.numeroContato }}</strong></li>
                                                 <li>E-mail: <strong>{{ associado.email }}</strong></li>
                                             </ul>
                                             <h5>Endereço Residencial</h5>
                                             <ul class="list-unstyled">
                                                 <li>CEP: <strong>{{ associado.cep }}</strong></li>
                                                 <li>Logradouro: <strong>{{ associado.logradouro }}</strong></li>
                                                 <li>Número: <strong>{{ associado.num }}</strong></li>
                                                 <li>Bairro: <strong>{{ associado.bairro }}</strong></li>
                                                 <li>Cidade: <strong>{{ associado.cidade }}</strong></li>
                                                 <li>Estado (UF): <strong>{{ associado.estado }}</strong></li>
                                             </ul>
                                         </div>
                                         <div class="col-md-6">
                                            {% if associado.dependentes.all %}
                                            <h5>Dependentes</h5>
                                            <ul class="list-unstyled">
                                                {% for dependente in associado.dependentes.all %}
                                                    <li class="mb-5">
                                                        <h6><strong>{{ dependente.nomecompleto }}</strong> </h6>

                                                        Data de Nascimento: <strong>{{ dependente.dataNascimento }}</strong><br>
                                                        Sexo: <strong>{{ dependente.get_sexo_display }}</strong><br>
                                                        CPF: <strong>{{ dependente.cpf }}</strong><br>
                                                        Identidade: <strong>{{ dependente.identidade }}</strong><br>
                                                        Órgão Emissor: <strong>{{ dependente.get_orgemissor_display }}</strong><br>
                                                        Grau de Parentesco: <strong>{{ dependente.get_grauparentesco_display }}</strong>
                                                        <div class="mt-3">
                                                            <a href="{% url 'editar_dependente' dependente.pk %}" class="btn btn-outline-warning me-md-2" type="button">
                                                                <i class="bi bi-pencil-square"></i>
                                                            </a>
                                                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete{{dependente.pk}}">
                                                           <i class="bi bi-trash3"></i>
                                                        </button>
                                                        <!-- Modal - Delete Associado -->
                                                        <div class="modal" id="delete{{dependente.pk}}" tabindex="-1" aria-labelledby="myModalLabel2" aria-hidden="true">
                                                            <div class="modal-dialog" role="document">
                                                              <div class="modal-content">
                                                                <div class="modal-header">
                                                                  <h5 class="modal-title">
                                                                   {{ dependente.nomecompleto }}
                                                                  </h5>
                                                                  <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close">
                                                                    <span aria-hidden="true"></span>
                                                                  </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                  <p>Deseja realmente excluir (a)o dependente ?</p>
                                                                </div>
                                                                <div class="modal-footer">
                                                                  <form action="{% url 'excluir_dependente' dependente.pk %}" method="POST">
                                                                    {% csrf_token %}
                                                                    <input type="submit" class="btn btn-primary" value="Delete">
                                                                  </form>
                                                                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                                                </div>
                                                              </div>
                                                            </div>
                                                        </div>
                                                        </div>
                                                    </li>
                                                {% endfor %}



                                            </ul>
                                             <a href="{% url 'cadastrar_dependentes' %}"> Deseja cadastrar outro ?</a>
                                            {% else %}
                                                <h5>Dependentes</h5>
                                                <p>Nenhum dependente cadastrado. <a href="{% url 'cadastrar_dependentes' %}"> Deseja cadastrar ?</a></p>
                                            {% endif %}
                                         </div>
                                     </div>

                                </div>

                                 <div class="card-footer">
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                            <a href='/associados/' class="btn btn-secondary me-md-2" type="button">Voltar</a>
                                            <button class="btn btn-primary" type="button">Imprimir</button>
                                    </div>
                                 </div>
                            </div>

        </div>

{% endblock content %}

blackpearl/associados/templates/associados/associado_form.html
{% extends "base_sidebar.html" %}

{% load crispy_forms_tags %}
{% load bootstrap5 %}
{% load static %}

{% block content %}
        <div class="container py-1">
          <div class="row d-flex justify-content-md-center align-items-center h-50">
            {% bootstrap_messages %}
              <form class="form-horizontal" action="" method="post" autocomplete="off" >
                  {% csrf_token %}
                 <div class="card shadow mb-3">
                     <h6 class="card-header">Dados pessoais e contatos</h6>
                     <div class="card-body">

                        <div class="row">
                            <div class="form-group  col-sm">

                              {{ form.nomecompleto|as_crispy_field }}
                            </div>
                        </div>

                        <div class="row">
                            <div class="from-group  col-sm">
                            {{ form.dataNascimento|as_crispy_field }}
                            </div>
                            <div class="from-group col-sm">
                              {{ form.sexo|as_crispy_field }}
                            </div>
                            <div class="from-group col-sm">

                              {{ form.estadocivil|as_crispy_field }}
                              </div>
                        </div>

                        <div class="row">
                              <div class="from-group col-sm">

                                {{ form.identidade|as_crispy_field }}
                              </div>
                              <div class="from-group  col-sm">

                                {{ form.orgemissor|as_crispy_field }}
                              </div>
                              <div class="from-group col-sm">

                                {{ form.cpf|as_crispy_field }}
                              </div>
                          </div>

                          <div class="row">
                                <div class="from-group col-sm">
                                    {{ form.dddNumeroContato|as_crispy_field }}
                                </div>
                                <div class="from-groupcol col-sm">
                                    {{ form.numeroContato|as_crispy_field }}
                                </div>
                                  <div class="from-group  col-sm">
                                    {{ form.email|as_crispy_field }}
                                  </div>
                            </div>
                     </div>
                </div>

                 <div class="card mb-3 ">
                          <h6 class="card-header">Endereço</h6>
                      <div class="card-body">
                        <div class="row">
                            <div class="col-6 col-md-4">
                                <div class="form-group col-sm">
                                    {{ form.cep|as_crispy_field }}
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group col-sm">
                                    {{ form.logradouro|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="from-groupcol col-sm">
                              {{ form.estado|as_crispy_field }}
                            </div>

                            <div class="from-group col-sm">
                              {{ form.cidade|as_crispy_field }}
                              </div>
                            <div class="from-group col-sm">
                                  {{ form.bairro|as_crispy_field }}
                              </div>
                            <div class="from-group col-sm">
                                  {{ form.num|as_crispy_field }}
                            </div>
                        </div>
                      </div>
                  </div>

                 <div class="card mb-3 ">
                      <h6 class="card-header">
                        Associação
                      </h6>
                  <div class="card-body">
                    <div class="row">
                            <div class="form-group col-sm">
                                {{ form.dataAssociacao|as_crispy_field }}
                            </div>
                           <div class="form-group col-sm">
                                {{ form.associacao|as_crispy_field }}
                            </div>
                            <div class="form-group col-sm">
                                {{ form.empresa|as_crispy_field }}
                            </div>
                           <div class="form-group col-sm">
                                {{ form.matricula|as_crispy_field }}
                            </div>
                    </div>
                  </div>

                 </div>
                  {% include 'button_save.html' %}
              </form>
              <script>

                const cepInput = document.querySelector('#cep');
                const addressInput = document.querySelector('#address');
                const regionInput = document.querySelector('#inputGroupSelectUF');
                const cityInput = document.querySelector('#textCidade');
                const neighborhoodInput = document.querySelector('#textBairro');
                const numeroInput = document.querySelector('#textNumero');


                cepInput.addEventListener('keypress', (e) => {
                  const onlyNumbers = /[0-9]|\./;
                  const key = String.fromCharCode(e.keyCode);

                  if (!onlyNumbers.test(key)) {
                    e.preventDefault();
                    return;
                  }
                });

                cepInput.addEventListener('keyup', (e) => {
                  const inputValue = e.target.value;

                  if (inputValue.length === 8) {
                    getAddress(inputValue);
                  }
                });
                function getAddress(cep) {
                  const numeroInput = document.querySelector('#numeroInput');

                  fetch(`https://viacep.com.br/ws/${cep}/json/`)
                    .then(response => response.json())
                    .then(data => {
                      console.log(data);
                      if (data.erro) {
                        alert('CEP não encontrado');
                        return;
                      }

                      addressInput.value = data.logradouro;
                      regionInput.value = data.uf;
                      cityInput.value = data.localidade;
                      neighborhoodInput.value = data.bairro;
                      numeroInput.focus();

                      formInputs.forEach((input) => {
                        if (input !== numeroInput) {
                          input.setAttribute('disabled', 'disabled');
                        }
                      });
                      numeroInput.removeAttribute('disabled');
                    })
                    .catch(error => console.log(error));
                }
          </script>
          </div>
        </div>
{% endblock content %}