blackpearl/convenios/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from blackpearl.convenios.views.homeViews import HomeTemplateView

from blackpearl.convenios.views.planoSaudeViews import ContratoPlanoSaudeCreateView, ContratoPlanoSaudeListView, \
    ContratoPlanoSaudeUpdateView, ContratoPlanoSaudeDeleteView, ContratoPlanoSaudeDetailView, ConsultaValorFaixaEtaria, \
    ContratoPlanoSaudeDependenteCreateView, ConsultaDependenteView, ConsultaValorFaixaEtariaDependente \
    , ContratoPlanoSaudeDependenteUpdateView, ContratoPlanoSaudeDependenteDeleteView, ContratoPlanoSaudeDependenteDetailView, \
    ContratoPlanoSaudeDependenteListView

from blackpearl.convenios.views.planoOdontologicoViews import ContratoPlanoOdontologicoCreateView, \
    ContratoPlanoOdontologicoDetailView, \
    ContratoPlanoOdontologicoUpdateView, ContratoPlanoOdontologicoDeleteView, ContratoOdontologicaListView, \
    ConsultaDosDependentesContratoPlanoOdontologicoView, VerificarAssociacaoView, DependentePlanoOdontologicoCreateView, ConsultaValoresPlanoOdontologicoDependente, \
    DependentePlanoOdontologicoListView, DependentePlanoOdontologicoUpdateView, DependentePlanoOdontologicoDeleteView, DependentePlanoOdontologicoDetailView

from blackpearl.convenios.views.cartaoVolusViews import CartaoListView, CartaoCreateView, CartaoUpdateView, CartaoDetailView, CartaoDeleteView, FaturaCreateView, FaturaListView, FaturaDeleteView, FaturaUpdateView, ConsultaTaxaView


urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home_conv'),
    path('cadastrarcartao/', CartaoCreateView.as_view(), name ='cartao_cadastrar'),
    path('detalhescartao/<int:pk>/', CartaoDetailView.as_view(), name ='cartao_visualizar'),
    path('editarcartao/<int:pk>/', CartaoUpdateView.as_view(), name ='cartao_editar'),
    path('excluircartao/<int:pk>/', CartaoDeleteView.as_view(), name ='cartao_excluir'),
    path('listagemcartoes/', CartaoListView.as_view(), name ='listagemcartoes'),



    path('editarfatura/<int:pk>/', FaturaUpdateView.as_view(), name ='fatura_editar'),
    path('excluirfatura/<int:pk>/', FaturaDeleteView.as_view(), name ='fatura_excluir'),
    path('cadastrarfatura/', FaturaCreateView.as_view(), name ='fatura_cadastrar'),
    path('listagemfaturas/', FaturaListView.as_view(), name ='listagemfaturas'),
    path('cartaovolus/consultataxa', ConsultaTaxaView.as_view(), name='consultataxa'),

    path('contratoodontologica/', ContratoPlanoOdontologicoCreateView.as_view(), name='contratoodontologica_cadastrar'),
    path('contratoodontologica/<int:pk>/detalhes/', ContratoPlanoOdontologicoDetailView.as_view(),name='contratoodontologico_visualizar'),
    path('contratoodontologica/<int:pk>/editar/', ContratoPlanoOdontologicoUpdateView.as_view(),name='contratoodontologico_editar'),
    path('contratoodontologica/<int:pk>/excluir', ContratoPlanoOdontologicoDeleteView.as_view(),name='contratoodontologico_excluir'),
    path('listagemcontratoodontologica/', ContratoOdontologicaListView.as_view(), name='listagemcontratoodontologica'),


    path('contratoondontologico/add/dependente', DependentePlanoOdontologicoCreateView.as_view(), name='cadastrar_dependente_plano_odontologico'),
    path('contratoondontologico/all/dependente', DependentePlanoOdontologicoListView.as_view(), name='listar_dependente_plano_odontologico'),
    path('contratoondontologico/dependente/<int:pk>/editar/', DependentePlanoOdontologicoUpdateView.as_view(), name='editar_dependente_plano_odontologico'),
    path('contratoondontologico/dependente/<int:pk>/excluir/', DependentePlanoOdontologicoDeleteView.as_view(), name='deletar_dependente_plano_odontologico'),
    path('contratoondontologico/dependente/<int:pk>/detalhar/', DependentePlanoOdontologicoDetailView.as_view(), name='detalhar_dependente_plano_odontologico'),


    path('contratoodontologica/verificarassociacao/', VerificarAssociacaoView.as_view(), name='verificar_associacao'),
    path('contratoondontologico/consultadosvalores/dependente/', ConsultaValoresPlanoOdontologicoDependente.as_view(), name='consultadosvalores'),
    path('contratoondontologico/consultadosdependentes/', ConsultaDosDependentesContratoPlanoOdontologicoView.as_view(), name='consultadosdependentes'),



    path('contratoplanosaude/add', ContratoPlanoSaudeCreateView.as_view(), name='cadastrar_contrato_plano_saude'),
    path('contratoplanosaude/all', ContratoPlanoSaudeListView.as_view(), name='listar_contratos_plano_saude'),
    path('contratoplanosaude/<int:pk>/editar', ContratoPlanoSaudeUpdateView.as_view(), name='editar_contrato_plano_saude'),
    path('contratoplanosaude/<int:pk>/excluir', ContratoPlanoSaudeDeleteView.as_view(), name='excluir_contrato_plano_saude'),
    path('contratoplanosaude/<int:pk>/detalhes', ContratoPlanoSaudeDetailView.as_view(), name='detalhes_contrato_plano_saude'),

    path('contratoplanosaude/add/dependente', ContratoPlanoSaudeDependenteCreateView.as_view(),name='cadastrar_dependentes_contrato_plano_saude'),
    path('contratoplanosaude/all/dependente', ContratoPlanoSaudeDependenteListView.as_view(),name='listar_dependentes_contrato_plano_saude'),
    path('contratoplanosaude/dependente/<int:pk>/editar/', ContratoPlanoSaudeDependenteUpdateView.as_view(),name='editar_dependentes_contrato_plano_saude'),
    path('contratoplanosaude/dependente/<int:pk>/excluir/', ContratoPlanoSaudeDependenteDeleteView.as_view(),name='excluir_dependentes_contrato_plano_saude'),
    path('contratoplanosaude/dependente/<int:pk>/delalhar/', ContratoPlanoSaudeDependenteDetailView.as_view(),name='detalhar_dependentes_contrato_plano_saude'),

    path('contratoplanosaude/consultafaixa/', ConsultaValorFaixaEtaria.as_view(), name='consultafaixa'),

    path('contratoplanosaude/consultadependente/', ConsultaDependenteView.as_view(), name='consulta_dependente'),
    path('contratoplanosaude/consultafaixa_dependente/', ConsultaValorFaixaEtariaDependente.as_view(), name='consulta_faixa_dependente'),



]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blackpearl/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blackpearl.usuarios.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('blackpearl.usuarios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('associados/', include('blackpearl.associados.urls')),
    path('convenios/', include('blackpearl.convenios.urls')),
    path('cobrancas/', include('blackpearl.cobrancas.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blackpearl/convenios/models/models.py
from django.db import models
from blackpearl.associados.models import ASSOCIACAO_CHOICES as ASSOCIACAO_CHOICES_ASSOCIADO


# Create your models here.
class Base(models.Model):
    criado = models.DateField('Data de Criação', auto_now_add=True)
    modificado = models.DateField('Data de Atualização', auto_now_add=True)
    ativo = models.BooleanField('Ativo?', default=True,  choices=[(True, 'Sim'), (False, 'Não')])

    class Meta:
        abstract = True



class Otica(Base):
    oticas_choices = [
        ('Ótica Telegrafo', 'Ótica Telegrafo'),
        ('Ótica Progressiva', 'Ótica Progressiva')
    ]
    nome = models.CharField('Nome da Ótica', max_length=40, choices=oticas_choices)
    cnpj = models.CharField('CNPJ', max_length=40)
    valorCompra = models.DecimalField('Valor da Compra', max_digits=8, decimal_places=2)


class TaxasAdministrativa(Base):
    ASSOCIACAO_CHOICES = ASSOCIACAO_CHOICES_ASSOCIADO
    ASSOCIACAO_CHOICES.append(
        ('outros', 'Outros')
    )

    grupos = models.CharField('Grupo', max_length=20, choices=ASSOCIACAO_CHOICES)
    percentual = models.DecimalField('Percetual da Taxa Administrativa (%)', max_digits=8, decimal_places=2)

    def __str__(self):
        return 'Taxa Administrativa: {}'.format(self.percentual)

blackpearl/convenios/forms/cartaoVolusForms.py
from django import forms

from django.template.defaultfilters import register

from blackpearl.convenios.models.cartaoVolusModels import CartaoConvenioVolus, FaturaCartao
from blackpearl.associados.models import Associado

class CartaoConvenioVolusForm(forms.ModelForm):
    class Meta:
        model = CartaoConvenioVolus
        exclude = ['ativo']
        fields = ['titular', 'valorLimite', 'status']

    def __int__(self, *args, **kwargs):
        super.__init__(*args, **kwargs)
        self.fields['titular'].queryset = Associado.objects.none()

        if 'titular' in self.data:
            self.fields['titular'].queryset = Associado.objects.all()
        elif self.instance.pk:
            self.fields['titular'].queryset = Associado.objects.all().filter(
                pk=self.instance.pk)


class FaturaCartaoForm(forms.ModelForm):
    class Meta:
        model = FaturaCartao
        exclude = ['ativo']
        fields = ['cartao', 'valor', 'valorComTaxa', 'competencia', 'situacaoFatura']
        widgets = {
            'competencia': forms.DateInput(
                attrs={
                    'class': 'form-control',
                    'type': 'date',
                }


            ),
            'valor': forms.NumberInput(
                attrs={
                    'class': 'form-control',
                    'step': '0.01'
                }
            ),
            'valorComTaxa': forms.NumberInput(
                attrs={
                    'class': 'form-control',
                    'disabled': 'disabled',
                    'step': '0.01',
                }
            ),
        }

class FileUploadExcelFaturasForm(forms.Form):
    arquivo = forms.FileField()
    arquivo.widget.attrs.update({'class': 'form-control-file'})
    arquivo.widget.attrs.update({'id': 'inputGroupFile'})
    arquivo.widget.attrs.update({'nome': 'arquivo'})
    class meta:

        fields = '__all__'
        widgets = {
            'arquivo': forms.FileField()
        }


@register.filter(name='add_class')
def add_class(field, css):
    return field.as_widget(attrs={"class": css})


@register.filter(name='add_placeholder')
def add_placeholder(field, text):
    return field.as_widget(attrs={"placeholder": text})

blackpearl/convenios/views/cartaoVolusViews.py
from decimal import Decimal

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView
from blackpearl.convenios.forms.cartaoVolusForms import CartaoConvenioVolusForm, FaturaCartaoForm, \
    FileUploadExcelFaturasForm
from blackpearl.convenios.models.cartaoVolusModels import CartaoConvenioVolus, FaturaCartao
from blackpearl.convenios.models.models import TaxasAdministrativa


@method_decorator(login_required, name='dispatch')
class CartaoListView(ListView):
    template_name = 'convenios/cartaoVolus/listagemcartoes.html'
    model = CartaoConvenioVolus
    paginate_by = 5
    context_object_name = 'list_objs'

    def get_queryset(self):
        queryset = super().get_queryset()
        nome_pesquisado = self.request.GET.get('obj')
        if nome_pesquisado:
            queryset = queryset.filter(titular__nomecompleto__icontains=nome_pesquisado).order_by('titular')
        else:
            queryset = queryset.all().order_by('titular')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


@method_decorator(login_required, name='dispatch')
class CartaoCreateView(CreateView):
    model = CartaoConvenioVolus
    form_class = CartaoConvenioVolusForm
    template_name = "convenios/cartaoVolus/cartaoconveniovolus_criar_form.html"
    success_url = reverse_lazy('listagemcartoes')

    def form_valid(self, form):
        cartao = form.save(commit=False)
        if ( cartao.valorLimite <=0):
            form.add_error('valorLimite', 'Valor do Limite deve ser maior que zero!')
            return self.form_invalid(form)
        cartao.save()
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class CartaoUpdateView(UpdateView):
    model = CartaoConvenioVolus
    form_class = CartaoConvenioVolusForm
    template_name = "convenios/cartaoVolus/cartaoconveniovolus_criar_form.html"
    success_url = reverse_lazy('listagemcartoes')


@method_decorator(login_required, name='dispatch')
class CartaoDetailView(DetailView):
    template_name = 'convenios/cartaoVolus/cartao_detalhes.html'
    model = CartaoConvenioVolus

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cartao_pk = self.kwargs['pk']
        cartao = CartaoConvenioVolus.objects.get(pk=cartao_pk)
        context['cartao'] = cartao
        return context


@method_decorator(login_required, name='dispatch')
class CartaoDeleteView(DeleteView):
    model = CartaoConvenioVolus
    success_url = reverse_lazy('listagemcartoes')


@method_decorator(login_required, name='dispatch')
class FaturaCreateView(CreateView):
    model = FaturaCartao
    form_class = FaturaCartaoForm

    template_name = "convenios/cartaoVolus/faturacartao_criar_form.html"

    def get_success_url(self):
        # Verifica a origem da solicitação na sessão
        origin = self.request.GET.get('origin', None)
        if origin == 'cartaodetalhes':
            cartao_pk = self.object.cartao.pk
            return reverse('cartao_visualizar', kwargs={'pk': cartao_pk})
        else:
            return reverse_lazy('listagemfaturas')

    def form_valid(self, form):
        fatura = form.save(commit=False)
        if ( fatura.valor > fatura.cartao.valorLimite ):
            form.add_error('valor', 'Valor da Fatura maior que o limite do cartão')
            return self.form_invalid(form)

        if ( fatura.valor < 0 ):
            form.add_error('valor', 'Valor da Fatura não pode ser negativo')
            return self.form_invalid(form)
        faturaExisteNaMesmaCompetencia = FaturaCartao.objects.filter(cartao=fatura.cartao,
                                                                     competencia__year=fatura.competencia.year,
                                                                     competencia__month=fatura.competencia.month).exists()
        if ( faturaExisteNaMesmaCompetencia ):
            form.add_error('competencia', 'Já existe uma fatura para esse cartão nessa competência')
            return self.form_invalid(form)

        fatura.save()
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class FaturaDeleteView(DeleteView):
    model = FaturaCartao
    success_url = reverse_lazy('listagemfaturas')


@method_decorator(login_required, name='dispatch')
class FaturaUpdateView(UpdateView):
    model = FaturaCartao
    form_class = FaturaCartaoForm
    template_name_suffix = "_criar_form"
    success_url = reverse_lazy('listagemfaturas')


@method_decorator(login_required, name='dispatch')
class FaturaListView(ListView):
    template_name = 'convenios/cartaoVolus/listagem_faturas.html'
    model = FaturaCartao
    context_object_name = 'list_objs'
    paginate_by = 5
    def get_queryset(self):
        queryset = super().get_queryset()
        nome_pesquisado = self.request.GET.get('obj')
        if nome_pesquisado:
            queryset = queryset.filter(cartao__titular__nomecompleto__icontains=nome_pesquisado).order_by('cartao')
        else:
            queryset = queryset.all().order_by('cartao')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


@method_decorator(login_required, name='dispatch')
class ConsultaTaxaView(View):
    @csrf_exempt
    def get(self, request):
        valor = self.request.GET.get('valor')
        try:
            taxa_administrativa = TaxasAdministrativa.objects.get(grupos='outros')
            percentual_taxa = taxa_administrativa.percentual
            taxa = 1 + (percentual_taxa / Decimal(100.0))
            valorTaxa = round(Decimal(valor) * taxa, 2)
            return JsonResponse({'valorTaxa': valorTaxa})
        except:
            return JsonResponse({'valorTaxa': 0})


@method_decorator(login_required, name='dispatch')
class ImportarFaturasView(View):
    template_name = "convenios/cartaoVolus/formsdimport_excel.html"
    form_class = FileUploadExcelFaturasForm()
    success_url = reverse_lazy('listagemfaturas')
    def get(self, request, *args, **kwargs):
        context = {
            'form': self.form_class,
        }
        return render(request, self.template_name, context)
    def post(self, request, *args, **kwargs):

        print(request.FILES)

blackpearl/convenios/templates/convenios/planoSaude/button_model_contrato_plano_saude_detail.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-success" data-toggle="modal" data-target="#staticBackdrop">
      <i class="bi bi-person-vcard"></i>
</button>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Detalhes de {{contrato.contratante.get_nomecompleto_display}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5>Dados do Contrato</h5>
        <ul class="list-unstyled">
              <li>Contratante: <strong>{{ contrato.contratante.get_nomecompleto_display }}</strong></li>
              <li>Contratado: <strong>{{ contrato.planoSaude }}</strong></li>
              <li>Faixa Etária: <strong>{{ contrato.faixa }} (anos)</strong></li>
              <li>Atendimento Domiciliar: <strong>{{ contrato.get_atedimentoDomiciliar_display }}</strong></li>
              <li>Forma de Pagemento: <strong>{{ contrato.formaPagamento }}</strong></li>
              <li>Valor Unitário: <strong>{{ contrato.valor }}</strong></li>
              <li>Valor total (Taxa Administrativa): <strong>{{ contrato.valorTotal }}</strong></li>
              <li>Data de Contratação: <strong>{{ contrato.dataInicio }}</strong></li>

              {% if contrato.ativo %}
                  <li>Status:
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="green" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/></svg>
                  </li>
              {% else %}
                  <li>Status:
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                        </svg>
                  </li>
              {% endif %}

        </ul>
        <h5>Dependentes</h5>
        {% if contrato.dependentes.all %}
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Dependente</th>
              <th scope="col">Grau de Parentesco</th>
              <th scope="col">Valor</th>
              <th scope="col">Data de Início</th>
              <th scope="col">Ativo</th>
              <th scope="col">Opção</th>
            </tr>
          </thead>
          <tbody>
            {% for dependente in contrato.dependentes.all %}
            <tr>
              <td>{{ dependente.dependente }}</td>
              <td>{{ dependente.dependente.get_grauparentesco_display }}</td>
              <td>{{ dependente.valorTotal }}</td>
              <td>{{ dependente.dataInicio }}</td>
              <td>{{ dependente.get__ativo_display }}</td>
              <td>
                    {% include 'buttons_crud_update.html' with href_update='editar_dependentes_contrato_plano_saude' obj=dependente.pk %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
          </table>
        {% else %}
        <p> Não há dependentes cadastrados </p>
        {% endif %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Sair</button>
        <button type="button" class="btn btn-primary">Imprimir</button>
      </div>
    </div>
  </div>
</div>

blackpearl/convenios/templates/convenios/planoSaude/listagem_contratos_plano_saude.html
{% extends "base_sidebar.html" %}
{% block content %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% load static %}

<div class="container-fluid">
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row align-items-center">
            <div class="col-md-4 ">
                <h4 class="m-0 font-weight-bold text-primary">Contratos dos Planos de Saúde</h4>
            </div>
        </div>
    </div>
    {% if list_objs %}
    {% include 'search.html' with href='listar_contratos_plano_saude' %}

    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered">
          <thead>
            <tr>
                <th scope="col">Titular - Contratante</th>
                <th scope="col">Plano Contratado</th>
                <th scope="col">Forma de Pagamento</th>
                <th scope="col">Valor (R$)</th>
                <th scope="col">Data de Início</th>

                <th scope="col">Status</th>
                <th scope="col">Opções</th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            {% for contratos in list_objs %}
            <tr>
              <td>{{ contratos.contratante }}</td>
              <td>{{ contratos.planoSaude }}</td>
              <td>{{ contratos.formaPagamento }} </td>
              <td>{{ contratos.valorTotal }}</td>
              <td>{{ contratos.dataInicio }}</td>

              <td>{{ contratos.get_ativo_display }}</td>
              <td>
                {% include 'convenios/planosaude/button_model_contrato_plano_saude_detail.html' with  contrato=contratos%}
                {% include 'buttons_crud_update.html' with href_update='editar_contrato_plano_saude' obj=contratos.pk %}
                {% include 'buttons_crud_delete.html' with href_delete='excluir_contrato_plano_saude' obj=contratos.pk obj_titulo=contratos.contratante%}
              </td>
              {% endfor %}
          </tbody>
        </table>
        {% include 'pagination.html' with href='listar_contratos_plano_saude'%}
      </div>
    </div>
    {% else %}
        <div class="card-body">
        <div class="d-flex gap-2 d-md-flex">
          <h4 class="m-0 font-weight-bold text-primary">Não há contratos cadastrados</h4>
        </div>
      </div>
    {% endif%}
</div>
</div>

{% endblock content %}

blackpearl/convenios/templates/convenios/planoSaude/listagem_dependentes_contrato_plano_saude.html
{% extends "base_sidebar.html" %}
{% block content %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% load static %}

<div class="container-fluid">
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row align-items-center">
            <div class="col-md-4 ">
                <h4 class="m-0 font-weight-bold text-primary">Contratos dos Planos de Saúde</h4>
            </div>
        </div>
    </div>
    {% if list_objs %}
    {% include 'search.html' with href='listar_dependentes_contrato_plano_saude' %}

    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered">
          <thead>
            <tr>
                <th scope="col">Dependente</th>
                <th scope="col">Titular</th>
                <th scope="col">Plano Contratado</th>
                <th scope="col">Valor (R$)</th>
                <th scope="col">Data de Início</th>

                <th scope="col">Status</th>
                <th scope="col">Opções</th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            {% for contratos in list_objs %}
            <tr>
              <td>{{ contratos.dependente.get_nomecompleto_display }}</td>
              <td>{{ contratos.contrato.contratante }}</td>
              <td>{{ contratos.contrato.planoSaude }} </td>
              <td>{{ contratos.valorTotal }}</td>
              <td>{{ contratos.dataInicio }}</td>

              <td>{{ contratos.get_ativo_display }}</td>
              <td>
                {% include 'convenios/planosaude/button_model_dependente_contrato_plano_saude_detail.html' with  contrato=contratos%}
                {% include 'buttons_crud_update.html' with href_update='editar_dependentes_contrato_plano_saude' obj=contratos.pk %}
                {% include 'buttons_crud_delete.html' with href_delete='excluir_dependentes_contrato_plano_saude' obj=contratos.pk obj_titulo=contratos.dependente%}
              </td>
              {% endfor %}
          </tbody>
        </table>
        {% include 'pagination.html' with href='listar_contratos_plano_saude'%}
      </div>
    </div>
    {% else %}
        <div class="card-body">
        <div class="d-flex gap-2 d-md-flex">
          <h4 class="m-0 font-weight-bold text-primary">Não há contratos cadastrados</h4>
        </div>
      </div>
    {% endif%}
</div>
</div>

{% endblock content %}