blackpearl/convenios/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from blackpearl.convenios.views.homeViews import HomeTemplateView

from blackpearl.convenios.views.planoSaudeViews import ContratoPlanoSaudeCreateView, ContratoPlanoSaudeListView, \
    ContratoPlanoSaudeUpdateView, ContratoPlanoSaudeDeleteView, ContratoPlanoSaudeDetailView, ConsultaValorFaixaEtaria, \
    ContratoPlanoSaudeDependenteCreateView, ConsultaDependenteView, ConsultaValorFaixaEtariaDependente \
    , ContratoPlanoSaudeDependenteUpdateView, ContratoPlanoSaudeDependenteDeleteView, ContratoPlanoSaudeDependenteDetailView, \
    ContratoPlanoSaudeDependenteListView

from blackpearl.convenios.views.planoOdontologicoViews import ContratoPlanoOdontologicoCreateView, \
    ContratoPlanoOdontologicoDetailView, \
    ContratoPlanoOdontologicoUpdateView, ContratoPlanoOdontologicoDeleteView, ContratoOdontologicaListView, \
    ConsultaDosDependentesContratoPlanoOdontologicoView, VerificarAssociacaoView, DependentePlanoOdontologicoCreateView, ConsultaValoresPlanoOdontologicoDependente, \
    DependentePlanoOdontologicoListView, DependentePlanoOdontologicoUpdateView, DependentePlanoOdontologicoDeleteView, DependentePlanoOdontologicoDetailView

from blackpearl.convenios.views.cartaoVolusViews import CartaoListView, CartaoCreateView, CartaoUpdateView, CartaoDetailView, CartaoDeleteView, FaturaCreateView, FaturaListView, FaturaDeleteView, FaturaUpdateView, ConsultaTaxaView


urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home_conv'),
    path('cadastrarcartao/', CartaoCreateView.as_view(), name ='cartao_cadastrar'),
    path('detalhescartao/<int:pk>/', CartaoDetailView.as_view(), name ='cartao_visualizar'),
    path('editarcartao/<int:pk>/', CartaoUpdateView.as_view(), name ='cartao_editar'),
    path('excluircartao/<int:pk>/', CartaoDeleteView.as_view(), name ='cartao_excluir'),
    path('listagemcartoes/', CartaoListView.as_view(), name ='listagemcartoes'),



    path('editarfatura/<int:pk>/', FaturaUpdateView.as_view(), name ='fatura_editar'),
    path('excluirfatura/<int:pk>/', FaturaDeleteView.as_view(), name ='fatura_excluir'),
    path('cadastrarfatura/', FaturaCreateView.as_view(), name ='fatura_cadastrar'),
    path('listagemfaturas/', FaturaListView.as_view(), name ='listagemfaturas'),
    path('cartaovolus/consultataxa', ConsultaTaxaView.as_view(), name='consultataxa'),

    path('contratoodontologica/', ContratoPlanoOdontologicoCreateView.as_view(), name='contratoodontologica_cadastrar'),
    path('contratoodontologica/<int:pk>/detalhes/', ContratoPlanoOdontologicoDetailView.as_view(),name='contratoodontologico_visualizar'),
    path('contratoodontologica/<int:pk>/editar/', ContratoPlanoOdontologicoUpdateView.as_view(),name='contratoodontologico_editar'),
    path('contratoodontologica/<int:pk>/excluir', ContratoPlanoOdontologicoDeleteView.as_view(),name='contratoodontologico_excluir'),
    path('listagemcontratoodontologica/', ContratoOdontologicaListView.as_view(), name='listagemcontratoodontologica'),


    path('contratoondontologico/add/dependente', DependentePlanoOdontologicoCreateView.as_view(), name='cadastrar_dependente_plano_odontologico'),
    path('contratoondontologico/all/dependente', DependentePlanoOdontologicoListView.as_view(), name='listar_dependente_plano_odontologico'),
    path('contratoondontologico/dependente/<int:pk>/editar/', DependentePlanoOdontologicoUpdateView.as_view(), name='editar_dependente_plano_odontologico'),
    path('contratoondontologico/dependente/<int:pk>/excluir/', DependentePlanoOdontologicoDeleteView.as_view(), name='deletar_dependente_plano_odontologico'),
    path('contratoondontologico/dependente/<int:pk>/detalhar/', DependentePlanoOdontologicoDetailView.as_view(), name='detalhar_dependente_plano_odontologico'),


    path('contratoodontologica/verificarassociacao/', VerificarAssociacaoView.as_view(), name='verificar_associacao'),
    path('contratoondontologico/consultadosvalores/dependente/', ConsultaValoresPlanoOdontologicoDependente.as_view(), name='consultadosvalores'),
    path('contratoondontologico/consultadosdependentes/', ConsultaDosDependentesContratoPlanoOdontologicoView.as_view(), name='consultadosdependentes'),



    path('contratoplanosaude/add', ContratoPlanoSaudeCreateView.as_view(), name='cadastrar_contrato_plano_saude'),
    path('contratoplanosaude/all', ContratoPlanoSaudeListView.as_view(), name='listar_contratos_plano_saude'),
    path('contratoplanosaude/<int:pk>/editar', ContratoPlanoSaudeUpdateView.as_view(), name='editar_contrato_plano_saude'),
    path('contratoplanosaude/<int:pk>/excluir', ContratoPlanoSaudeDeleteView.as_view(), name='excluir_contrato_plano_saude'),
    path('contratoplanosaude/<int:pk>/detalhes', ContratoPlanoSaudeDetailView.as_view(), name='detalhes_contrato_plano_saude'),

    path('contratoplanosaude/add/dependente', ContratoPlanoSaudeDependenteCreateView.as_view(),name='cadastrar_dependentes_contrato_plano_saude'),
    path('contratoplanosaude/all/dependente', ContratoPlanoSaudeDependenteListView.as_view(),name='listar_dependentes_contrato_plano_saude'),
    path('contratoplanosaude/dependente/<int:pk>/editar/', ContratoPlanoSaudeDependenteUpdateView.as_view(),name='editar_dependentes_contrato_plano_saude'),
    path('contratoplanosaude/dependente/<int:pk>/excluir/', ContratoPlanoSaudeDependenteDeleteView.as_view(),name='excluir_dependentes_contrato_plano_saude'),
    path('contratoplanosaude/dependente/<int:pk>/delalhar/', ContratoPlanoSaudeDependenteDetailView.as_view(),name='detalhar_dependentes_contrato_plano_saude'),

    path('contratoplanosaude/consultafaixa/', ConsultaValorFaixaEtaria.as_view(), name='consultafaixa'),

    path('contratoplanosaude/consultadependente/', ConsultaDependenteView.as_view(), name='consulta_dependente'),
    path('contratoplanosaude/consultafaixa_dependente/', ConsultaValorFaixaEtariaDependente.as_view(), name='consulta_faixa_dependente'),



]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blackpearl/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blackpearl.usuarios.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('blackpearl.usuarios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('associados/', include('blackpearl.associados.urls')),
    path('convenios/', include('blackpearl.convenios.urls')),
    path('cobrancas/', include('blackpearl.cobrancas.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blackpearl/convenios/models/cartaoVolusModels.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.urls import reverse
from _decimal import Decimal
from blackpearl.associados.models import Associado
from blackpearl.convenios.models.models import TaxasAdministrativa, Base


class CartaoConvenioVolus(Base):
    status_choices = [
        ('ATIVO', 'ATIVO'),
        ('SUSPENSO', 'SUSPENSO'),
        ('CANCELADO', 'CANCELADO')
    ]
    nome = models.CharField('Nome do Cartão', max_length=20, default='Convênio Volus')
    titular = models.ForeignKey(Associado, on_delete=models.CASCADE, related_name='cartaovolus')
    valorLimite = models.DecimalField('Valor do Limite', max_digits=8, decimal_places=2)
    status = models.CharField('Status', max_length=20, choices=status_choices)

    def __str__(self):
        return '{}'.format(self.titular)

    def get_absolute_url(self):
        return reverse("cartao_cadastrar", kwargs={"pk": self.pk})


class FaturaCartao(Base):
    SITUACAOFATURA_CHOICES = [
        ('ABERTA', 'ABERTA'),
        ('PAGA', 'PAGA'),
        ('CANCELADA', 'CANCELADA')
    ]
    cartao = models.ForeignKey(CartaoConvenioVolus, on_delete=models.CASCADE, related_name='faturas')
    valor = models.DecimalField('Valor da Fatura', max_digits=8, decimal_places=2)
    valorComTaxa = models.DecimalField('Valor da Fatura com a Taxa Adm', max_digits=8, decimal_places=2, null=True,
                                       blank=True)
    competencia = models.DateField('Competência')

    situacaoFatura = models.CharField('Situação da Fatura', max_length=20, choices=SITUACAOFATURA_CHOICES,
                                      default=SITUACAOFATURA_CHOICES[0][0])
    def __str__(self):
        return 'Valor da fatura e competência: {}  / {}'.format(self.valor, self.competencia)


@receiver(pre_save, sender=FaturaCartao)
def aplicar_taxa_adm_cartao(sender, instance, *args, **kwargs):
    taxa_administrativa = TaxasAdministrativa.objects.get(grupos='outros')
    percentual_taxa = taxa_administrativa.percentual
    taxa = 1 + (percentual_taxa / Decimal(100.0))
    instance.valorComTaxa = instance.valor * taxa

blackpearl/cobrancas/views/homeView.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView


from blackpearl.cobrancas.models.faturaCobrancaModels import CobrancaPlanoSaude, CobrancaPlanoOdontologico, FaturaCobranca

@method_decorator(login_required, name='dispatch')
class FaturaCobrancaListView(ListView):
    template_name = 'home_cob.html'

    context_object_name = 'list_objs'
    paginate_by = 10

    def get_queryset(self):
        cobrancas_plano_saude = CobrancaPlanoSaude.objects.all()
        cobrancas_plano_odontologico = CobrancaPlanoOdontologico.objects.all()

        todas_cobrancas = list(cobrancas_plano_saude) + list(cobrancas_plano_odontologico)

        todas_cobrancas.sort(key=lambda x: x.situacao)
        return todas_cobrancas


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(FaturaCobrancaListView, self).get_context_data(**kwargs)
        context['list_obs'] = self.get_queryset()

        return context

blackpearl/convenios/views/cartaoVolusViews.py
from decimal import Decimal

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView
from blackpearl.convenios.forms.cartaoVolusForms import CartaoConvenioVolusForm, FaturaCartaoForm, \
    FileUploadExcelFaturasForm
from blackpearl.convenios.models.cartaoVolusModels import CartaoConvenioVolus, FaturaCartao
from blackpearl.convenios.models.models import TaxasAdministrativa


@method_decorator(login_required, name='dispatch')
class CartaoListView(ListView):
    template_name = 'convenios/cartaoVolus/listagemcartoes.html'
    model = CartaoConvenioVolus
    paginate_by = 5
    context_object_name = 'list_objs'

    def get_queryset(self):
        queryset = super().get_queryset()
        nome_pesquisado = self.request.GET.get('obj')
        if nome_pesquisado:
            queryset = queryset.filter(titular__nomecompleto__icontains=nome_pesquisado).order_by('titular')
        else:
            queryset = queryset.all().order_by('titular')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


@method_decorator(login_required, name='dispatch')
class CartaoCreateView(CreateView):
    model = CartaoConvenioVolus
    form_class = CartaoConvenioVolusForm
    template_name = "convenios/cartaoVolus/cartaoconveniovolus_criar_form.html"
    success_url = reverse_lazy('listagemcartoes')

    def form_valid(self, form):
        cartao = form.save(commit=False)
        if ( cartao.valorLimite <=0):
            form.add_error('valorLimite', 'Valor do Limite deve ser maior que zero!')
            return self.form_invalid(form)
        cartao.save()
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class CartaoUpdateView(UpdateView):
    model = CartaoConvenioVolus
    form_class = CartaoConvenioVolusForm
    template_name = "convenios/cartaoVolus/cartaoconveniovolus_criar_form.html"
    success_url = reverse_lazy('listagemcartoes')


@method_decorator(login_required, name='dispatch')
class CartaoDetailView(DetailView):
    template_name = 'convenios/cartaoVolus/cartao_detalhes.html'
    model = CartaoConvenioVolus

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cartao_pk = self.kwargs['pk']
        cartao = CartaoConvenioVolus.objects.get(pk=cartao_pk)
        context['cartao'] = cartao
        return context


@method_decorator(login_required, name='dispatch')
class CartaoDeleteView(DeleteView):
    model = CartaoConvenioVolus
    success_url = reverse_lazy('listagemcartoes')


@method_decorator(login_required, name='dispatch')
class FaturaCreateView(CreateView):
    model = FaturaCartao
    form_class = FaturaCartaoForm

    template_name = "convenios/cartaoVolus/faturacartao_criar_form.html"

    def get_success_url(self):
        # Verifica a origem da solicitação na sessão
        origin = self.request.GET.get('origin', None)
        if origin == 'cartaodetalhes':
            cartao_pk = self.object.cartao.pk
            return reverse('cartao_visualizar', kwargs={'pk': cartao_pk})
        else:
            return reverse_lazy('listagemfaturas')

    def form_valid(self, form):
        fatura = form.save(commit=False)
        if ( fatura.valor > fatura.cartao.valorLimite ):
            form.add_error('valor', 'Valor da Fatura maior que o limite do cartão')
            return self.form_invalid(form)

        if ( fatura.valor < 0 ):
            form.add_error('valor', 'Valor da Fatura não pode ser negativo')
            return self.form_invalid(form)
        faturaExisteNaMesmaCompetencia = FaturaCartao.objects.filter(cartao=fatura.cartao,
                                                                     competencia__year=fatura.competencia.year,
                                                                     competencia__month=fatura.competencia.month).exists()
        if ( faturaExisteNaMesmaCompetencia ):
            form.add_error('competencia', 'Já existe uma fatura para esse cartão nessa competência')
            return self.form_invalid(form)

        fatura.save()
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class FaturaDeleteView(DeleteView):
    model = FaturaCartao
    success_url = reverse_lazy('listagemfaturas')


@method_decorator(login_required, name='dispatch')
class FaturaUpdateView(UpdateView):
    model = FaturaCartao
    form_class = FaturaCartaoForm
    template_name_suffix = "_criar_form"
    success_url = reverse_lazy('listagemfaturas')


@method_decorator(login_required, name='dispatch')
class FaturaListView(ListView):
    template_name = 'convenios/cartaoVolus/listagem_faturas.html'
    model = FaturaCartao
    context_object_name = 'list_objs'
    paginate_by = 5
    def get_queryset(self):
        queryset = super().get_queryset()
        nome_pesquisado = self.request.GET.get('obj')
        if nome_pesquisado:
            queryset = queryset.filter(cartao__titular__nomecompleto__icontains=nome_pesquisado).order_by('cartao')
        else:
            queryset = queryset.all().order_by('cartao')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


@method_decorator(login_required, name='dispatch')
class ConsultaTaxaView(View):
    @csrf_exempt
    def get(self, request):
        valor = self.request.GET.get('valor')
        try:
            taxa_administrativa = TaxasAdministrativa.objects.get(grupos='outros')
            percentual_taxa = taxa_administrativa.percentual
            taxa = 1 + (percentual_taxa / Decimal(100.0))
            valorTaxa = round(Decimal(valor) * taxa, 2)
            return JsonResponse({'valorTaxa': valorTaxa})
        except:
            return JsonResponse({'valorTaxa': 0})


@method_decorator(login_required, name='dispatch')
class ImportarFaturasView(View):
    template_name = "convenios/cartaoVolus/formsdimport_excel.html"
    form_class = FileUploadExcelFaturasForm()
    success_url = reverse_lazy('listagemfaturas')
    def get(self, request, *args, **kwargs):
        context = {
            'form': self.form_class,
        }
        return render(request, self.template_name, context)
    def post(self, request, *args, **kwargs):

        print(request.FILES)

blackpearl/convenios/templates/convenios/contratacaoodontologica.html
{% extends "base_sidebar.html" %}
{% load crispy_forms_tags %}
{% block bootstrap5_content %}
{% load bootstrap5 %}
{% load static %}

    <!-- Usado para construção do Datatables -->
      <link href="https://cdn.datatables.net/v/bs5/jq-3.6.0/jszip-2.5.0/dt-1.13.4/b-2.3.6/b-html5-2.3.6/b-print-2.3.6/datatables.min.css" rel="stylesheet"/>
      <div class="container">
         <div class="row d-flex justify-content-center align-items-center h-50 mt-5">
         {% bootstrap_messages %}
         <form class="form-horizontal" action="{% url 'contratacaoodontologica' %}" method="post" autocomplete="off" >
                  {% csrf_token %}
                 <div class="card mb-3">
                     <h6 class="card-header">Contratação do Plano Odontologico</h6>
                     <div class="card-body">
                        <div class="row">
                            <div class="form-group  col-sm">

                              {{ form.contratante|as_crispy_field }}
                            </div>
                             <div class="from-group col-sm">

                              {{ form.plano_odontologico|as_crispy_field }}
                            </div>
                            <div class="form-group  col-sm">

                              {{ form.valor|as_crispy_field }}
                            </div>
                        </div>
                          <div class="row mt-2" >
                                            <div class="from-group col-sm">
                                                {{ form.dependentes|as_crispy_field }}
                                            </div>
                          </div>


                         <div class="d-grid gap-2 mt-5 d-md-flex justify-content-md-end">
                            {% buttons %}
                            <button type="submit" class="btn btn-primary">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill-add" viewBox="0 0 16 16">
                                  <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0Zm-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                                  <path d="M2 13c0 1 1 1 1 1h5.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.544-3.393C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4Z"/>
                                </svg>
                                Contratar
                            </button>
                            {% endbuttons %}
                        </div>
                     </div>
                 </div>
              </form>

         </div>
      </div>


{% bootstrap_javascript %}
{% endblock bootstrap5_content %}

blackpearl/convenios/templates/convenios/formsdjango.html
{% extends "base_sidebar.html" %}
{% load crispy_forms_tags %}
{% load bootstrap5 %}
{% load static %}

{% block bootstrap5_content %}
<div class="container py-1">
          <div class="row d-flex justify-content-md-center align-items-center h-50">

            {% bootstrap_messages %}

              <form class="form-horizontal" action="{% url 'cadastrarCartao' %}" method="post" autocomplete="off" >
                  {% csrf_token %}
                 <div class="card mb-3">
                     <h6 class="card-header">Cadastro de Cartão</h6>
                     <div class="card-body">

                        <div class="row">
                            <div class="form-group  col-sm">

                              {{ form.titular|as_crispy_field }}
                            </div>
                        </div>

                        <div class="row">
                            <div class="from-group  col-sm">

                              {{ form.valorLimite|as_crispy_field }}
                            </div>
                            <div class="from-group col-sm">

                              {{ form.status|as_crispy_field }}
                            </div>

                        </div>
                         <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        {% buttons %}
                        <button type="submit" class="btn btn-primary">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill-add" viewBox="0 0 16 16">
                              <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0Zm-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                              <path d="M2 13c0 1 1 1 1 1h5.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.544-3.393C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4Z"/>
                            </svg>
                            Salvar</button>
                        {% endbuttons %}
                   </div>
                   </div>
                 </div>
              </form>
          </div>
        </div>


{% bootstrap_javascript %}
{% endblock bootstrap5_content %}

blackpearl/convenios/templates/convenios/formsfatura.html
{% extends "base_sidebar.html" %}
{% load crispy_forms_tags %}
{% load bootstrap5 %}
{% load static %}

{% block bootstrap5_content %}
<div class="container py-5">
          <div class="row d-flex justify-content-md-center align-items-center h-50">
            {% bootstrap_messages %}

              <form class="form-horizontal" action="{% url 'cadastrarFatura' %}" method="post" autocomplete="off" >
                  {% csrf_token %}
                 <div class="card mb-3">
                     <h6 class="card-header">Cadastro de Fatura do Cartão Volus</h6>
                     <div class="card-body">
                        <div class="row">
                            <div class="form-group  col-sm">

                              {{ form.cartao|as_crispy_field }}
                            </div>
                             <div class="from-group col-sm">

                              {{ form.competencia|as_crispy_field }}
                            </div>
                        </div>
                         <div class="row">
                            <div class="from-group  col-sm">

                              {{ form.valor|as_crispy_field }}
                            </div>

                            <div class="from-group  col-sm">
                              {{ form.valorComTaxa|as_crispy_field }}
                            </div>
                         </div>

                         <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            {% buttons %}
                            <button type="submit" class="btn btn-primary">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill-add" viewBox="0 0 16 16">
                                  <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0Zm-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                                  <path d="M2 13c0 1 1 1 1 1h5.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.544-3.393C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4Z"/>
                                </svg>
                                Salvar
                            </button>
                            {% endbuttons %}
                        </div>
                     </div>
                 </div>
              </form>
              <script>
            $(document).ready(function() {
                // Define as variáveis necessárias
                var valorField = $('#id_valor');
                var valorComTaxaField = $('#id_valorComTaxa');
                var valor = parseFloat(valorField.val());

                // Atualiza o valor do campo "valorComTaxa" ao mudar o valor do campo "valor"
                valorField.on('input', function() {
                    valor = parseFloat(valorField.val());
                    if (!isNaN(valor)) {
                        valorComTaxaField.val((valor * 1.05).toFixed(2));
                    } else {
                        valorComTaxaField.val('');
                    }
                });
            });
            </script>
          </div>
</div>

{% bootstrap_javascript %}
{% endblock bootstrap5_content %}

blackpearl/convenios/templates/convenios/home.html
{% extends "base_sidebar.html" %}

{% block bootstrap5_content %}
{% load bootstrap5 %}
{% load static %}

      <div class="container">
         <div class="row d-flex justify-content-center align-items-center h-50 mt-5">

             <div class="container overflow-hidden ">
              <div class="row gy-5">
                <div class="col-6">
                  <div class="p-3">
                       <div class="card" >
                        <div class="card-body">
                          <h5 class="card-title">Oticas</h5>
                          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                          <a href="#" class="btn btn-primary">Go somewhere</a>
                        </div>
                      </div>
                  </div>
                </div>
                <div class="col-6">
                  <div class="p-3">
                       <div class="card" >
                        <div class="card-body">
                          <h5 class="card-title">Oticas</h5>
                          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                          <a href="#" class="btn btn-primary">Go somewhere</a>
                        </div>
                      </div>
                  </div>
                </div>
                <div class="col-6">
                  <div class="p-3">
                       <div class="card" >
                        <div class="card-body">
                          <h5 class="card-title">Cartão Volus</h5>
                          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                          <a href="/convenios/cadastrar" class="btn btn-primary">Novo Cartão</a>
                        </div>
                      </div>
                  </div>
                </div>
                <div class="col-6">
                  <div class="p-3">
                       <div class="card" >
                        <div class="card-body">
                          <h5 class="card-title">Oticas</h5>
                          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                          <a href="#" class="btn btn-primary">Go somewhere</a>
                        </div>
                      </div>
                  </div>
                </div>
              </div>
            </div>


         </div>
      </div>


{% endblock bootstrap5_content %}

blackpearl/convenios/templates/convenios/listagemcontratacaoodontologica.html
{% extends "base_sidebar.html" %}

{% block bootstrap5_content %}
{% load bootstrap5 %}
{% load static %}

    <!-- Usado para construção do Datatables -->
      <link href="https://cdn.datatables.net/v/bs5/jq-3.6.0/jszip-2.5.0/dt-1.13.4/b-2.3.6/b-html5-2.3.6/b-print-2.3.6/datatables.min.css" rel="stylesheet"/>
        <div class="container">
          <div class="row d-flex justify-content-center align-items-center h-50 mt-5">
            <h4 class="">Associados com Plano odontologico</h4>
            {% include 'search.html' with href='listarcontratacaoodontologica' %}
            <table class="table table-hover" >
                        <thead>
                          <tr>
                            <th scope="col">Titular - Contratante</th>
                            <th scope="col">Plano Contratado</th>
                            <th scope="col">Valor (R$)</th>
                            <th scope="col">Dependentes</th>
                            <th scope="col">Opções</th>
                          </tr>
                        </thead>
                            <tbody class="table-group-divider">

                              {% for contratos in list_objs %}
                              <tr>

                              <td>{{ contratos.contratante }}</td>
                                <td>{{ contratos.plano_odontologico }}</td>
                              <td>{{ contratos.valor }}</td>
                                <td>{{contratos.dependentes.count}}</td>

                              </tr>
                              {% endfor %}

                          </tbody>
                       </table>
            {% include 'pagination.html' with href='listarcontratacaoodontologica'%}
          </div>
        </div>


{% endblock bootstrap5_content %}