blackpearl/convenios/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from blackpearl.convenios.views.homeViews import HomeTemplateView

from blackpearl.convenios.views.planoSaudeViews import ContratoPlanoSaudeCreateView, ContratoPlanoSaudeListView, \
    ContratoPlanoSaudeUpdateView, ContratoPlanoSaudeDeleteView, ContratoPlanoSaudeDetailView, ConsultaValorFaixaEtaria, \
    ContratoPlanoSaudeDependenteCreateView, ConsultaDependenteView, ConsultaValorFaixaEtariaDependente \
    , ContratoPlanoSaudeDependenteUpdateView, ContratoPlanoSaudeDependenteDeleteView, ContratoPlanoSaudeDependenteDetailView, \
    ContratoPlanoSaudeDependenteListView

from blackpearl.convenios.views.planoOdontologicoViews import ContratoPlanoOdontologicoCreateView, \
    ContratoPlanoOdontologicoDetailView, \
    ContratoPlanoOdontologicoUpdateView, ContratoPlanoOdontologicoDeleteView, ContratoOdontologicaListView, \
    ConsultaDosDependentesContratoPlanoOdontologicoView, VerificarAssociacaoView, DependentePlanoOdontologicoCreateView, ConsultaValoresPlanoOdontologicoDependente, \
    DependentePlanoOdontologicoListView, DependentePlanoOdontologicoUpdateView, DependentePlanoOdontologicoDeleteView, DependentePlanoOdontologicoDetailView

from blackpearl.convenios.views.cartaoVolusViews import CartaoListView, CartaoCreateView, CartaoUpdateView, CartaoDetailView, CartaoDeleteView, FaturaCreateView, FaturaListView, FaturaDeleteView, FaturaUpdateView, ConsultaTaxaView


urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home_conv'),
    path('cadastrarcartao/', CartaoCreateView.as_view(), name ='cartao_cadastrar'),
    path('detalhescartao/<int:pk>/', CartaoDetailView.as_view(), name ='cartao_visualizar'),
    path('editarcartao/<int:pk>/', CartaoUpdateView.as_view(), name ='cartao_editar'),
    path('excluircartao/<int:pk>/', CartaoDeleteView.as_view(), name ='cartao_excluir'),
    path('listagemcartoes/', CartaoListView.as_view(), name ='listagemcartoes'),



    path('editarfatura/<int:pk>/', FaturaUpdateView.as_view(), name ='fatura_editar'),
    path('excluirfatura/<int:pk>/', FaturaDeleteView.as_view(), name ='fatura_excluir'),
    path('cadastrarfatura/', FaturaCreateView.as_view(), name ='fatura_cadastrar'),
    path('listagemfaturas/', FaturaListView.as_view(), name ='listagemfaturas'),
    path('cartaovolus/consultataxa', ConsultaTaxaView.as_view(), name='consultataxa'),

    path('contratoodontologica/', ContratoPlanoOdontologicoCreateView.as_view(), name='contratoodontologica_cadastrar'),
    path('contratoodontologica/<int:pk>/detalhes/', ContratoPlanoOdontologicoDetailView.as_view(),name='contratoodontologico_visualizar'),
    path('contratoodontologica/<int:pk>/editar/', ContratoPlanoOdontologicoUpdateView.as_view(),name='contratoodontologico_editar'),
    path('contratoodontologica/<int:pk>/excluir', ContratoPlanoOdontologicoDeleteView.as_view(),name='contratoodontologico_excluir'),
    path('listagemcontratoodontologica/', ContratoOdontologicaListView.as_view(), name='listagemcontratoodontologica'),


    path('contratoondontologico/add/dependente', DependentePlanoOdontologicoCreateView.as_view(), name='cadastrar_dependente_plano_odontologico'),
    path('contratoondontologico/all/dependente', DependentePlanoOdontologicoListView.as_view(), name='listar_dependente_plano_odontologico'),
    path('contratoondontologico/dependente/<int:pk>/editar/', DependentePlanoOdontologicoUpdateView.as_view(), name='editar_dependente_plano_odontologico'),
    path('contratoondontologico/dependente/<int:pk>/excluir/', DependentePlanoOdontologicoDeleteView.as_view(), name='deletar_dependente_plano_odontologico'),
    path('contratoondontologico/dependente/<int:pk>/detalhar/', DependentePlanoOdontologicoDetailView.as_view(), name='detalhar_dependente_plano_odontologico'),


    path('contratoodontologica/verificarassociacao/', VerificarAssociacaoView.as_view(), name='verificar_associacao'),
    path('contratoondontologico/consultadosvalores/dependente/', ConsultaValoresPlanoOdontologicoDependente.as_view(), name='consultadosvalores'),
    path('contratoondontologico/consultadosdependentes/', ConsultaDosDependentesContratoPlanoOdontologicoView.as_view(), name='consultadosdependentes'),



    path('contratoplanosaude/add', ContratoPlanoSaudeCreateView.as_view(), name='cadastrar_contrato_plano_saude'),
    path('contratoplanosaude/all', ContratoPlanoSaudeListView.as_view(), name='listar_contratos_plano_saude'),
    path('contratoplanosaude/<int:pk>/editar', ContratoPlanoSaudeUpdateView.as_view(), name='editar_contrato_plano_saude'),
    path('contratoplanosaude/<int:pk>/excluir', ContratoPlanoSaudeDeleteView.as_view(), name='excluir_contrato_plano_saude'),
    path('contratoplanosaude/<int:pk>/detalhes', ContratoPlanoSaudeDetailView.as_view(), name='detalhes_contrato_plano_saude'),

    path('contratoplanosaude/add/dependente', ContratoPlanoSaudeDependenteCreateView.as_view(),name='cadastrar_dependentes_contrato_plano_saude'),
    path('contratoplanosaude/all/dependente', ContratoPlanoSaudeDependenteListView.as_view(),name='listar_dependentes_contrato_plano_saude'),
    path('contratoplanosaude/dependente/<int:pk>/editar/', ContratoPlanoSaudeDependenteUpdateView.as_view(),name='editar_dependentes_contrato_plano_saude'),
    path('contratoplanosaude/dependente/<int:pk>/excluir/', ContratoPlanoSaudeDependenteDeleteView.as_view(),name='excluir_dependentes_contrato_plano_saude'),
    path('contratoplanosaude/dependente/<int:pk>/delalhar/', ContratoPlanoSaudeDependenteDetailView.as_view(),name='detalhar_dependentes_contrato_plano_saude'),

    path('contratoplanosaude/consultafaixa/', ConsultaValorFaixaEtaria.as_view(), name='consultafaixa'),

    path('contratoplanosaude/consultadependente/', ConsultaDependenteView.as_view(), name='consulta_dependente'),
    path('contratoplanosaude/consultafaixa_dependente/', ConsultaValorFaixaEtariaDependente.as_view(), name='consulta_faixa_dependente'),



]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blackpearl/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blackpearl.usuarios.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('blackpearl.usuarios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('associados/', include('blackpearl.associados.urls')),
    path('convenios/', include('blackpearl.convenios.urls')),
    path('cobrancas/', include('blackpearl.cobrancas.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blackpearl/convenios/models/models.py
from django.db import models
from blackpearl.associados.models import ASSOCIACAO_CHOICES as ASSOCIACAO_CHOICES_ASSOCIADO


# Create your models here.
class Base(models.Model):
    criado = models.DateField('Data de Criação', auto_now_add=True)
    modificado = models.DateField('Data de Atualização', auto_now_add=True)
    ativo = models.BooleanField('Ativo?', default=True,  choices=[(True, 'Sim'), (False, 'Não')])

    class Meta:
        abstract = True



class Otica(Base):
    oticas_choices = [
        ('Ótica Telegrafo', 'Ótica Telegrafo'),
        ('Ótica Progressiva', 'Ótica Progressiva')
    ]
    nome = models.CharField('Nome da Ótica', max_length=40, choices=oticas_choices)
    cnpj = models.CharField('CNPJ', max_length=40)
    valorCompra = models.DecimalField('Valor da Compra', max_digits=8, decimal_places=2)


class TaxasAdministrativa(Base):
    ASSOCIACAO_CHOICES = ASSOCIACAO_CHOICES_ASSOCIADO
    ASSOCIACAO_CHOICES.append(
        ('outros', 'Outros')
    )

    grupos = models.CharField('Grupo', max_length=20, choices=ASSOCIACAO_CHOICES)
    percentual = models.DecimalField('Percetual da Taxa Administrativa (%)', max_digits=8, decimal_places=2)

    def __str__(self):
        return 'Taxa Administrativa: {}'.format(self.percentual)

blackpearl/convenios/models/planoSaudeModels.py
from django.db import models
from django.urls import reverse
from blackpearl.associados.models import Associado, Dependente
from blackpearl.convenios.models.models import Base

class PlanoSaude(Base):
    planos_choices = [
        ('Unimed - Max Nacional', 'Unimed - Max Nacional'),
        ('Unimed - Grupo de Municipios', 'Unimed - Grupo de Municipios'),

    ]
    segmentacao_choices = [
        ('Apartamento', 'Apartamento'),
        ('Enfermaria', 'Enfermaria')
    ]

    nome = models.CharField("Nome do Plano", max_length=100, choices=planos_choices)
    cnpj = models.CharField('CNPJ', max_length=40, default="04.201.372/0001-37")
    contrato = models.CharField('Número do Contrato', max_length=10)
    segmentacao = models.CharField('Segmentação', max_length=20, choices=segmentacao_choices)
    valorAtendimentoDomiciliar = models.DecimalField("Valor do Atendimento Domiciliar", max_digits=5, decimal_places=2)
    valorAtendimentoTelefonico = models.DecimalField("Valor do Atendimento Telefonico", max_digits=5, decimal_places=2, default=3.2)
    def __str__(self):
        return '{} - {}'.format(self.nome, self.segmentacao)


class ValoresPorFaixa(Base):
    planoSaude = models.ForeignKey(PlanoSaude, on_delete=models.CASCADE, related_name='faixas')
    idadeMin = models.IntegerField('Idade Minima')
    idadeMax = models.IntegerField('Idade Max')
    valor = models.DecimalField('Valor da Faixa', max_digits=6, decimal_places=2)

    def __str__(self):
        return '{} a {} (anos)'.format(self.idadeMin, self.idadeMax)

class ContratoPlanoSaude(Base):
    contratante = models.OneToOneField(Associado, on_delete=models.CASCADE, related_name='contratos_saude')
    planoSaude = models.ForeignKey(PlanoSaude, on_delete=models.CASCADE, related_name='contratos')

    faixa = models.ForeignKey(ValoresPorFaixa, on_delete=models.CASCADE, related_name='contratos_contratante')

    atendimentoDomiciliar = models.BooleanField('Atendimento Domiciliar', default=False, choices=[(True, 'Sim'), (False, 'Não')])

    dataInicio = models.DateField('Data da Contratação')
    dataFim = models.DateField('Data do Cancelamento', blank=True, null=True)

    formaPagamento = models.CharField('Forma de Pagamento', max_length=20,
                                      choices=[('Boleto Bancário', 'Boleto Bancário'),
                                               ('Desconto em folha', 'Desconto em folha'),
                                               ('Isento', 'Isento')])
    valor = models.DecimalField('Valor do Unitário', max_digits=8, decimal_places=2)
    valorTotal = models.DecimalField('Valor do Contrato', max_digits=8, decimal_places=2, null=True, blank=True)

    def get_atedimentoDomiciliar_display(self):
        if self.atendimentoDomiciliar:
            return 'Sim'
        else:
            return 'Não'
    def get_ativo_display(self):
        if self.ativo:
            return 'Sim'
        else:
            return 'Não'
    def dataFim_display(self):
        if self.dataFim:
            return self.dataFim
        else:
            return 'Vigente'
    def __str__(self):
        return '{} - {}'.format(self.contratante, self.planoSaude)

    def get_absolute_url(self):
        return reverse("contrato_cadastrar", kwargs={"pk": self.pk})
class ContratoPlanoSaudeDependente(Base):
    contrato = models.ForeignKey(ContratoPlanoSaude, on_delete=models.CASCADE, related_name='dependentes')
    dependente = models.OneToOneField(Dependente, on_delete=models.CASCADE, related_name='contrato_saude')
    valor = models.DecimalField('Valor Unitário', max_digits=8, decimal_places=2)
    dataInicio = models.DateField('Data de Início')
    dataFim = models.DateField('Data de Fim', null=True, blank=True)
    atendimentoDomiciliar = models.BooleanField('Atendimento Domiciliar', default=False,
                                                choices=[(True, 'Sim'), (False, 'Não')])

    faixa = models.ForeignKey(ValoresPorFaixa, on_delete=models.CASCADE, related_name='contratos_dependente')
    valorTotal = models.DecimalField('Valor do Contrato', max_digits=8, decimal_places=2, null=True, blank=True)
    def get__ativo_display(self):
        return 'Sim' if self.ativo else 'Não'

    def get__dataFim_display(self):
        if not self.dataFim:
            return "Vigente"
        else:
            return str(self.valor)

blackpearl/convenios/views/homeViews.py
from io import BytesIO
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from reportlab.pdfgen import canvas
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from blackpearl.convenios.models.cartaoVolusModels import FaturaCartao


@method_decorator(login_required, name='dispatch')
class HomeTemplateView(TemplateView):
    template_name = 'convenios/home_cob.html'

    def get_context_data(self, **kwargs):
        context = super(HomeTemplateView, self).get_context_data(**kwargs)
        return context


"""
def exportar(request):
    empresa_selecionada = request.GET.get('inputGroupSelectEmpresa')
    data_inicial = request.GET.get('start_date')
    data_final = request.GET.get('end_date')
    tipoArquivo_selecionado = request.GET.get('inputGroupSelectTipoArquivo')

    print(f"{empresa_selecionada}, {data_inicial}, {data_final}")

    if data_inicial and data_final and empresa_selecionada and tipoArquivo_selecionado:
        # Filtra as faturas pelo intervalo de datas e pelo nome da empresa
        if empresa_selecionada == '5':
            faturas = FaturaCartao.objects.filter(
                competencia__gte=data_inicial, competencia__lte=data_final
            ).order_by('competencia')

            nome_arq = 'faturas_{}_{}'.format(data_inicial, data_final)
        else:
            faturas = FaturaCartao.objects.filter(
                cartao__titular__empresa_id=empresa_selecionada,
                competencia__gte=data_inicial, competencia__lte=data_final
            ).order_by('competencia')
            nome_arq = 'fatura_{}_{}'.format(data_inicial, data_final)

        return exporttofile(faturas=faturas,
                            nome_arq=nome_arq,
                            tipoArquivo_selecionado=tipoArquivo_selecionado)

    return reverse_lazy('listagemfaturas')


def exporttofile(faturas, nome_arq, tipoArquivo_selecionado):
    global response
    filename = f"{nome_arq}"

    if tipoArquivo_selecionado == '1':

        quant_faturas = faturas.count()
        buffer = BytesIO()
        pdf = canvas.Canvas(buffer)
        y = 750  # Posição y inicial
        for fatura in faturas:
            if y <= 50:
                pdf.showPage()
                y = 750
            # Escreve o título da fatura
            pdf.drawString(100, y, "Titular do Cartão: {}".format(fatura.cartao.titular.nomecompleto))
            y -= 20  # Move para a próxima linha
            pdf.drawString(100, y, "Empresa: {}".format(fatura.cartao.titular.empresa.nome))
            y -= 20  # Move para a próxima linha
            # Escreve as informações da fatura
            pdf.drawString(100, y, "Competência: {}".format(fatura.competencia))
            y -= 20
            pdf.drawString(100, y, "Valor: {}".format(fatura.valorComTaxa))
            y -= 40  # Move duas linhas para baixo

        pdf.save()
        # Define o nome do arquivo PDF
        filename = filename + ".pdf"
        # Envia o PDF para o navegador como um arquivo de download
        response = HttpResponse(content_type='application/pdf')

        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        buffer.seek(0)

        response.write(buffer.read())

        buffer.close()
    elif tipoArquivo_selecionado == '2':
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = nome_arq
        # Escreve os dados da lista de faturas na planilha
        ws['A1'] = "Titular - Associado(a)"
        ws['B1'] = "Empresa"
        ws['C1'] = "Competêcia"
        ws['D1'] = "Valor"


        for i, fatura in enumerate(faturas):
            ws.cell(row=i + 2, column=1, value=fatura.cartao.titular.nomecompleto)
            ws.cell(row=i + 2, column=2, value=fatura.cartao.titular.empresa.nome)
            ws.cell(row=i + 2, column=3, value=fatura.competencia)
            ws.cell(row=i + 2, column=4, value=fatura.valorComTaxa)

        # Cria uma resposta HTTP com o arquivo XLSX
        response = HttpResponse(content_type='application/xlsx')
        response['Content-Disposition'] = f'attachment; filename={nome_arq}.xlsx'
        wb.save(response)


    elif tipoArquivo_selecionado == '3':
        faturas_txt = ''
        for fatura in faturas:
            matricula = str(fatura.cartao.titular.matricula).zfill(6)
            valorComTaxa = str(fatura.valorComTaxa)[:4].replace('.', '').zfill(12)
            faturas_txt += '{} {}\n'.format(matricula, valorComTaxa)

        response = HttpResponse(faturas_txt, content_type='text/plain')
        response['Content-Disposition'] = f'attachment; filename="{nome_arq}.txt'

    return response
"""

blackpearl/convenios/templates/convenios/planoOdontologico/button_view_model_contratos_plano_odont.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-success" data-toggle="modal" data-target="#staticBackdrop">
      <i class="bi bi-person-vcard"></i>
</button>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Detalhes de {{contrato.contratante.get_nomecompleto_display}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5>Dados do Contrato</h5>
        <ul class="list-unstyled">
          <li>Contratante: <strong>{{ contrato.contratante }}</strong></li>
          <li>Contratado: <strong>{{ contrato.planoOdontologico }}</strong></li>
          <li>Valor Unitário: <strong>{{ contrato.planoOdontologico.valorUnitario }}</strong></li>
          <li>Valor com Taxa: <strong>{{ contrato.valor }}</strong></li>
          <li>Forma de Pagemento: <strong>{{ contrato.formaPagamento }}</strong></li>
          <li>Data de Contratação: <strong>{{ contrato.dataInicio }}</strong></li>
          <li>Ativo: <strong>{{ contrato.get_ativo_display }}</strong></li>
        </ul>
        <h5>Dependentes</h5>
        {% if contrato.dependentes.all %}
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Dependente</th>
              <th scope="col">Grau de Parentesco</th>
              <th scope="col">Valor Unitário</th>
              <th scope="col">Valor com Taxa</th>
              <th scope="col">Data de Início</th>
              <th scope="col">Ativo</th>
            </tr>
          </thead>
          <tbody>
            {% for dependente in contrato.dependentes.all %}
            <tr>
              <td>{{ dependente.dependente }}</td>
              <td>{{ dependente.dependente.get_grauparentesco_display }}</td>
              <td>{{ dependente.valor }}</td>
              <td>{{ dependente.valorComTaxa }}</td>
              <td>{{ dependente.dataInicio }}</td>
              <td>{{ dependente.get__ativo_display }}</td>
            </tr>
            {% endfor %}
          </tbody>
          </table>
        {% else %}
        <p> Não há dependentes cadastrados </p>
        {% endif %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Sair</button>
        <button type="button" class="btn btn-primary">Imprimir</button>
      </div>
    </div>
  </div>
</div>

blackpearl/convenios/templates/convenios/planoOdontologico/button_view_model_dependente_contratos_plano_odont.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-success" data-toggle="modal" data-target="#staticBackdrop">
      <i class="bi bi-person-vcard"></i>
</button>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Detalhes de {{contrato.contratante.get_nomecompleto_display}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5>Dados do contrato do dependente {{contrato.dependente.get_nomecompleto_display}}</h5>

        <ul class="list-unstyled">
            <li>Titular: {{contrato.contratoTitular.contratante}}</li>
            <li>Dependente: {{contrato.dependente.get_nomecompleto_display}}</li>
            <li>Grau de Parêntesco: {{contrato.dependente.get_grauparentesco_display}}</li>
            <li>Ativo: {{contrato.get__ativo_display}}</li>
            <li>Valor Unitário: {{contrato.valor}}</li>
            <li>Valor com Taxa: {{contrato.valorComTaxa}}</li>
            <li>Data de Início: {{contrato.dataInicio}}</li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Sair</button>
        <button type="button" class="btn btn-primary">Imprimir</button>
      </div>
    </div>
  </div>
</div>

blackpearl/convenios/templates/convenios/planoOdontologico/contratacaoplanoodontologico_criar_form.html
{% extends "base_sidebar.html" %}
{% load i18n %}


{% block content_script %}
    <script src="/static/convenios/contratoPlanoOdontologicoTitularAdd.js"></script>
{% endblock content_script %}


{% block content %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% load static %}
    <!-- Usado para construção do Datatables -->
      <div class="container">
         <div class="row d-flex justify-content-center align-items-center h-50 mt-5">
         {% bootstrap_messages %}
         <form class="form-horizontal" action="" method="post" >
                  {% csrf_token %}
                 <div class="card mb-3">
                     <h6 class="card-header">Contratação do Plano Odontologico</h6>
                     <div class="card-body">
                        <div class="row">
                            <div class="form-group row col-sm">
                                {{form.contratante|as_crispy_field}}
                            </div>

                             <div class="form-group row col-sm">
                                {{form.dataInicio|as_crispy_field}}
                            </div>
                            <div class="form-group row col-sm">
                                {{form.ativo|as_crispy_field}}
                            </div>
                        </div>
                         <div class="row">

                             <div class="form-group row col-sm">
                                {{form.planoOdontologico|as_crispy_field}}
                            </div>
                             <div class="form-group row col-sm">
                                {{form.formaPagamento|as_crispy_field}}
                            </div>
                            <div class="form-group row col-sm">
                                {{form.valor|as_crispy_field}}
                            </div>
                        </div>
                        {% include 'button_save_loading.html' %}
                     </div>
                 </div>

              </form>
         </div>
      </div>
{% bootstrap_javascript %}
{% endblock content %}

blackpearl/convenios/templates/convenios/planoOdontologico/listagem_contratacaoodontologica.html
{% extends "base_sidebar.html" %}
{% block content %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% load static %}

<div class="container-fluid">
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row align-items-center">
            <div class="col-md-4 ">
                <h4 class="m-0 font-weight-bold text-primary">Contratos do Plano Odontologico</h4>
            </div>
        </div>
    </div>
    {% if list_objs %}
    {% include 'search.html' with href='listagemcontratoodontologica' %}
            <div class="card-body">
                <div class="table-responsive">
                  <table class="table table-bordered" >
                        <thead>
                          <tr>
                            <th scope="col">Titular - Contratante</th>
                            <th scope="col">Plano Contratado</th>
                            <th scope="col">Forma de Pagamento</th>
                            <th scope="col">Valor (R$)</th>
                            <th scope="col">Data de Início</th>
                            <th scope="col">Data de Término</th>
                            <th scope="col">Ativo</th>
                            <th scope="col">Opções</th>
                          </tr>
                        </thead>
                            <tbody class="table-group-divider">

                              {% for contratos in list_objs %}
                              <tr>
                                <td>{{ contratos.contratante }}</td>
                                <td>{{ contratos.planoOdontologico }}</td>
                                <td>{{ contratos.formaPagamento }}</td>
                                <td>{{ contratos.valor }}</td>
                                <td>{{ contratos.dataInicio }}</td>
                                <td>{{ contratos.get_dataFim_display }}</td>
                                <td>{{ contratos.get_ativo_display }}</td>
                                <td>
                                  {% include 'convenios/planoOdontologico/button_view_model_contratos_plano_odont.html' with  contrato=contratos%}
                                  {% include 'buttons_crud_update.html' with href_update='contratoodontologico_editar' obj=contratos.pk %}
                                  {% include 'buttons_crud_delete.html' with href_delete='contratoodontologico_excluir' obj=contratos.pk obj_titulo=contratos.contratante%}
                                </td>
                              </tr>
                              {% endfor %}

                          </tbody>
                       </table>
            {% include 'pagination.html' with href='listagemcontratoodontologica'%}
          </div>
        </div>
    {% else %}
      <div class="card-body">
        <div class="d-flex gap-2 d-md-flex">
          <h4 class="m-0 font-weight-bold text-primary">Não há contratos cadastrados</h4>
        </div>
      </div>
  {% endif%}
  </div>
</div>

{% endblock content %}